### ISSUE TITLE
error TS5023: Unknown compiler option 'moduleResolution'. while npm start

### ISSUE THREAD

**Issue by ketulrastogi** [vimalavinisha/angular2-google-chart#1]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.8.6
3 info using node@v6.1.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular2-google-chart@1.0.0~prestart: angular2-google-chart@1.0.0
6 silly lifecycle angular2-google-chart@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle angular2-google-chart@1.0.0~start: angular2-google-chart@1.0.0
8 verbose lifecycle angular2-google-chart@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-google-chart@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\playground\chart-tests\angular2-google-chart\node_modules\.bin;C:\Program Files\nodejs;C:\Ruby193\bin;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Git\cmd;C:\Program Files\Common Files\Autodesk Shared\;C:\MongoDB\bin;C:\Python35;C:\Python35\Scripts;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Ketul\AppData\Roaming\npm
10 verbose lifecycle angular2-google-chart@1.0.0~start: CWD: D:\playground\chart-tests\angular2-google-chart
11 silly lifecycle angular2-google-chart@1.0.0~start: Args: [ '/d /s /c',
11 silly lifecycle   'tsc && concurrently "npm run tsc:w" "npm run lite" ' ]
12 silly lifecycle angular2-google-chart@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle angular2-google-chart@1.0.0~start: Failed to exec start script
14 verbose stack Error: angular2-google-chart@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid angular2-google-chart@1.0.0
16 verbose cwd D:\playground\chart-tests\angular2-google-chart
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.1.0
20 error npm  v3.8.6
21 error code ELIFECYCLE
22 error angular2-google-chart@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
22 error Exit status 1
23 error Failed at the angular2-google-chart@1.0.0 start script 'tsc && concurrently "npm run tsc:w" "npm run lite" '.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-google-chart package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     tsc && concurrently "npm run tsc:w" "npm run lite"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-google-chart
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-google-chart
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by rajan-g** [comment]
Hi ketulrastogi,
    We understand  this issue, it is like dependency missing issue. We fixed this one, now you can check with latest one.
