### ISSUE TITLE
Can't bind to 'chartData' since it isn't a known property of 'div'

### ISSUE THREAD

**Issue by MalinGunasekara** [vimalavinisha/angular2-google-chart#17]
i me getting this error on console.

Can't bind to 'chartData' since it isn't a known property of 'div'

**Comment by henkverschoor1994** [comment]
How did you solved this? I got the same error.

**Comment by CelebratedPooper** [comment]
[https://github.com/vimalavinisha/angular2-google-chart/issues/25](url) this helped me. I guess the important part is to import _GoogleChart_

**Comment by MorlaRamakrishna** [comment]
Hey, I got the same error,

**Comment by vimalavinisha** [comment]
Hi

Please ref the below link to solve this issue
https://github.com/vimalavinisha/angular2-google-chart/issues/25

I hope that you have missed to import GoogleChart Directive properly.
