### ISSUE TITLE
Please add support for Angular 4

### ISSUE THREAD

**Issue by BaKou** [vimalavinisha/angular2-google-chart#29]
currently when updating to angular 4 we are getting the below warning:

npm WARN ng2-charts@1.5.0 requires a peer of @angular/common@^2.3.0 but none was installed.
npm WARN ng2-charts@1.5.0 requires a peer of @angular/core@^2.3.0 but none was installed.

**Comment by vimalaanthony** [comment]
Hi,
Module upgraded to angular 4 version.
