### ISSUE TITLE
template parse error

### ISSUE THREAD

**Issue by zebadey** [vimalavinisha/angular2-google-chart#4]
this template doesn't work for me. i get an error 
EXCEPTION: Error: Uncaught (in promise): Template parse errors:
Only void and foreign elements can be self closed "div" ("

    [ERROR ->]<div id="line_chart",[chartData]="line_ChartData", [chartOptions] = "line_ChartOptions",chartType="Li"): 
template:  `
    <div id="line_chart",[chartData]="line_ChartData", [chartOptions] = "line_ChartOptions",chartType="LineChart",GoogleChart/>
    <div id="bubble_chart",[chartData]="bubble_ChartData", [chartOptions] = "bubble_ChartOptions",chartType="BubbleChart",GoogleChart/>
    <div id="scatter_chart",[chartData]="scatter_ChartData", [chartOptions] = "scatter_ChartOptions",chartType="ScatterChart",GoogleChart/>
    <div id="candle_chart",[chartData]="candle_ChartData", [chartOptions] = "candle_ChartOptions",chartType="CandlestickChart",GoogleChart/>    
    <div id="pie_chart",[chartData]="pie_ChartData", [chartOptions] = "pie_ChartOptions",chartType="PieChart",GoogleChart/>    
    <div id="bar_chart",[chartData]="bar_ChartData", [chartOptions] = "bar_ChartOptions",chartType="BarChart",GoogleChart/>`

**Comment by rajan-g** [comment]
Hi zebadey,
       I fix this issue, it is like wrong template formate please remove comma's from template.
